server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;
    return 444;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name _;

    ssl_certificate /etc/letsencrypt/live/botamin-151-243-3-142.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/botamin-151-243-3-142.nip.io/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 444;
}
